---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sec.sovereign.io
  resources:
  - sovereignsensors
  - sovereigntypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sec.sovereign.io
  resources:
  - sovereignsensors/finalizers
  - sovereigntypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - sec.sovereign.io
  resources:
  - sovereignsensors/status
  - sovereigntypolicies/status
  verbs:
  - get
  - patch
  - update
