apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      # Bind the Least Privilege ServiceAccount
      serviceAccountName: {{ .Chart.Name }}-sa
      
      # CRITICAL: We need hostNetwork to talk to the local Tetragon DaemonSet
      hostNetwork: true
      
      containers:
        - name: sensor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TETRAGON_SERVER
              value: {{ .Values.tetragon.serverAddress | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi