apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: sovereign-sensor-controller-manager-api
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sovereign-sensor
    control-plane: controller-manager
  name: sovereign-sensor-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: sovereign-sensor
    control-plane: controller-manager